# Generated by Django 5.0.6 on 2024-06-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BLACK', 'black'), ('WHITE', 'white'), ('RED', 'red'), ('GRAPHITE', 'graphite')], max_length=16)),
                ('car_types', models.CharField(choices=[('SUV', 'SUV'), ('SPORT', 'sport'), ('STANDARD', 'standard')], max_length=16)),
                ('model', models.CharField(max_length=100)),
                ('seats', models.PositiveSmallIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
