# Generated by Django 5.0.6 on 2024-06-07 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_klient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klient',
            new_name='Client',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('reservation_days', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=0, editable=False, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
            ],
        ),
    ]
