# Generated by Django 5.0.6 on 2024-06-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_klient_client_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_types',
            new_name='car_type',
        ),
    ]
