# Generated by Django 5.0.6 on 2024-06-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
